name: Run tests

on:
    pull_request:
        types: [opened, synchronize]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Check repo
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            - name: Install dependencies
              run : |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Test with pytest
              run: pytest services/tests
